language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

branches:
  only:
    - hexo

before_install:
  - export TZ='Asia/Taipei'

install:
  - npm install hexo-cli -g
  - npm install

before_script:
  - sed -i'' "s~https://github.com/anemology/anemology.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/anemology/anemology.github.io.git~" _config.yml
  - sed -i'' "s~CommitMessageWillReplacedByTravisCI~${TRAVIS_COMMIT_MESSAGE//$'\n'/' '}~" _config.yml

script:
  - hexo clean
  - hexo generate
  - git clone --depth 1 -b master https://github.com/anemology/anemology.github.io .deploy_git
  - hexo deploy
